# .github/workflows/ci.yml

name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Clone gohugoio/hugoBasicExample repository'
        run: |
          git clone https://github.com/gohugoio/hugoBasicExample.git
          cd hugoBasicExample
          git checkout 61c64dcf16b654f535787beba597ebcfa0f06bb6
          mv content/post content/posts
          sed -i 's/posts/post/g' content/posts/_index.md
          mkdir content/about && mv content/about.md content/about/_index.md
          mkdir -p themes/meme

      - name: 'Check out MemE into themes/meme folder'
        uses: actions/checkout@v4
        with:
          path: hugoBasicExample/themes/meme

      - name: 'Setup MemE'
        run: |
          cd hugoBasicExample
          rm -rf config*
          cp themes/meme/exampleSite/hugo.toml .

      - name: 'Install Hugo'
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: 'Build site'
        run: |
          cd hugoBasicExample
          hugo --gc --minify --cleanDestinationDir --baseURL="https://io-oi.me/hugo-theme-meme/"

      - name: 'Deploy to GitHub Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hugoBasicExample/public
          force_orphan: true
